# Generated by Django 4.2.7 on 2025-08-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="newsletter",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sms_notifications",
            field=models.BooleanField(default=False, verbose_name="Notifications SMS"),
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="auth_user_profile",
        ),
    ]
