# Generated by Django 4.2.7 on 2025-08-06 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titre")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("construction", "Construction"),
                            ("services", "Services"),
                            ("supplies", "Fournitures"),
                            ("consulting", "Conseil"),
                            ("maintenance", "Maintenance"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("closed", "Fermé"),
                            ("cancelled", "Annulé"),
                            ("awarded", "Attribué"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Organisme"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Personne de contact"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de contact"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone de contact"
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "deadline_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date limite de soumission"
                    ),
                ),
                (
                    "opening_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'ouverture des plis"
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Valeur estimée",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Lieu d'exécution"
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="Région"),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="URL source")),
                (
                    "scraped_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Extrait le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "content_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Hash du contenu"
                    ),
                ),
            ],
            options={
                "verbose_name": "Appel d'offres",
                "verbose_name_plural": "Appels d'offres",
                "ordering": ["-publication_date", "-scraped_at"],
            },
        ),
        migrations.CreateModel(
            name="TenderSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du site"
                    ),
                ),
                ("url", models.URLField(verbose_name="URL du site")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "last_scraped",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière extraction"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Site d'appels d'offres",
                "verbose_name_plural": "Sites d'appels d'offres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Nom du document"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("cahier_charges", "Cahier des charges"),
                            ("reglement", "Règlement de consultation"),
                            ("annexe", "Annexe"),
                            ("plan", "Plan"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(blank=True, verbose_name="URL du fichier"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Chemin du fichier local",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Taille du fichier (bytes)"
                    ),
                ),
                (
                    "downloaded",
                    models.BooleanField(default=False, verbose_name="Téléchargé"),
                ),
                (
                    "download_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de téléchargement"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenders.tender",
                        verbose_name="Appel d'offres",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document d'appel d'offres",
                "verbose_name_plural": "Documents d'appels d'offres",
                "ordering": ["document_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="tender",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenders",
                to="tenders.tendersite",
                verbose_name="Site source",
            ),
        ),
        migrations.CreateModel(
            name="ScrapingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échec"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Démarré le"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                (
                    "items_found",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Items trouvés"
                    ),
                ),
                (
                    "items_new",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nouveaux items"
                    ),
                ),
                (
                    "items_updated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Items mis à jour"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Temps d'exécution (secondes)",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraping_logs",
                        to="tenders.tendersite",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de scraping",
                "verbose_name_plural": "Logs de scraping",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(
                fields=["status", "deadline_date"], name="tenders_ten_status_10959e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(
                fields=["site", "scraped_at"], name="tenders_ten_site_id_6f7e5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(
                fields=["category", "status"], name="tenders_ten_categor_796c0b_idx"
            ),
        ),
    ]
