# Generated by Django 4.2.7 on 2025-08-05 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom du plan")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Gratuit"),
                            ("basic", "Basique"),
                            ("premium", "Premium"),
                            ("enterprise", "Entreprise"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Type de plan",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Prix",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensuel"),
                            ("yearly", "Annuel"),
                            ("lifetime", "À vie"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Cycle de facturation",
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="0 = illimité",
                        verbose_name="Nombre maximum d'utilisateurs",
                    ),
                ),
                (
                    "max_projects",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="0 = illimité",
                        verbose_name="Nombre maximum de projets",
                    ),
                ),
                (
                    "storage_limit_gb",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="0 = illimité",
                        verbose_name="Limite de stockage (GB)",
                    ),
                ),
                (
                    "has_api_access",
                    models.BooleanField(default=False, verbose_name="Accès API"),
                ),
                (
                    "has_priority_support",
                    models.BooleanField(
                        default=False, verbose_name="Support prioritaire"
                    ),
                ),
                (
                    "has_analytics",
                    models.BooleanField(
                        default=False, verbose_name="Analyses avancées"
                    ),
                ),
                (
                    "has_custom_branding",
                    models.BooleanField(
                        default=False, verbose_name="Personnalisation de marque"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Plan d'abonnement",
                "verbose_name_plural": "Plans d'abonnement",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("cancelled", "Annulé"),
                            ("expired", "Expiré"),
                            ("pending", "En attente"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "next_billing_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Prochaine facturation"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "is_trial",
                    models.BooleanField(default=False, verbose_name="Période d'essai"),
                ),
                (
                    "trial_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de l'essai"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Carte bancaire, PayPal, etc.",
                        max_length=50,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID de transaction"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="subscription.plan",
                        verbose_name="Plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "ordering": ["-created_at"],
                "unique_together": {("user", "plan", "status")},
            },
        ),
        migrations.CreateModel(
            name="SubscriptionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Créé"),
                            ("upgraded", "Mis à niveau"),
                            ("downgraded", "Rétrogradé"),
                            ("renewed", "Renouvelé"),
                            ("cancelled", "Annulé"),
                            ("expired", "Expiré"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "new_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_subscriptions",
                        to="subscription.plan",
                        verbose_name="Nouveau plan",
                    ),
                ),
                (
                    "old_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_subscriptions",
                        to="subscription.plan",
                        verbose_name="Ancien plan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="subscription.subscription",
                        verbose_name="Abonnement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'abonnement",
                "verbose_name_plural": "Historiques d'abonnement",
                "ordering": ["-created_at"],
            },
        ),
    ]
