# Generated by Django 4.2.7 on 2025-08-06 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0013_add_password_reset_token"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTemporaryPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'attribution"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Date à laquelle cette permission expire",
                        verbose_name="Date d'expiration",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cette permission est actuellement active",
                        verbose_name="Permission active",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date à laquelle cette permission a été révoquée manuellement",
                        null=True,
                        verbose_name="Date de révocation",
                    ),
                ),
                (
                    "test_background_color",
                    models.CharField(
                        default="yellow",
                        help_text="Couleur de fond pour tester les permissions d'abonnement payant (jaune par défaut)",
                        max_length=20,
                        verbose_name="Couleur de fond de test",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                        verbose_name="Permission",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="L'abonnement qui a accordé cette permission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_permissions",
                        to="subscription.subscription",
                        verbose_name="Abonnement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission temporaire utilisateur",
                "verbose_name_plural": "Permissions temporaires utilisateurs",
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="subscriptio_user_id_e9876d_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "is_active"],
                        name="subscriptio_expires_733c8b_idx",
                    ),
                ],
                "unique_together": {("user", "permission", "subscription")},
            },
        ),
        migrations.CreateModel(
            name="PlanPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cette permission est active pour ce plan",
                        verbose_name="Permission active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                        verbose_name="Permission",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_permissions",
                        to="subscription.plan",
                        verbose_name="Plan d'abonnement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission de plan",
                "verbose_name_plural": "Permissions de plans",
                "ordering": ["plan__name", "permission__name"],
                "unique_together": {("plan", "permission")},
            },
        ),
        migrations.CreateModel(
            name="PermissionMigrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("GRANT", "Permission accordée"),
                            ("REVOKE", "Permission révoquée"),
                            ("EXPIRE", "Permission expirée"),
                            ("RENEW", "Permission renouvelée"),
                            ("MIGRATE", "Migration de plan"),
                        ],
                        max_length=10,
                        verbose_name="Action",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Informations supplémentaires sur l'action",
                        verbose_name="Détails",
                    ),
                ),
                (
                    "new_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migration_logs_new",
                        to="subscription.plan",
                        verbose_name="Nouveau plan",
                    ),
                ),
                (
                    "old_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migration_logs_old",
                        to="subscription.plan",
                        verbose_name="Ancien plan",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                        verbose_name="Permission",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.subscription",
                        verbose_name="Abonnement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de migration de permission",
                "verbose_name_plural": "Journaux de migration de permissions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="subscriptio_user_id_082269_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="subscriptio_action_677bfd_idx",
                    ),
                ],
            },
        ),
    ]
